
language: node_js
node_js:
  - "6.10.2"

branches:
  only:
    - master

before_script:
  - npm install -g bower grunt firebase-tools
  - npm install
  - bower install

script:
  - grunt --force

after_success:
  - firebase deploy --token $FIREBASE_TOKEN
